### ISSUE TITLE
Is length site-round specific?

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#15]
Should there be a different length for each site or a different length for each site-round combination?

**Comment by sethapp** [comment]
Great question and I can see why that's confusing. I'm assuming you are referencing the site metadata table. In 2016 the length changed sometimes between site rounds but only for cre1, nkn1, nkn2, sie1, and pre1. (this was not intended but happened due to field mistakes). Length of each site is independent from other sites. Each site can be a different length. The length for each site and round in 2016 are contained in 'r1_transect_length', 'r2_transect_length', and 'r3_transect_length' columns in ISUmonarch/data-raw/Site Metadata Git 4-7-17.xlsx 

In 2017 length is the same within a single site, across all 3 rounds. The 2017 length is in the column 'final_transect_length'.

**Comment by jarad** [comment]
Fixed in fa686ae
