### ISSUE TITLE
NCIG Report: Table 1&2

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#21]
From Seth:

> Sum(round 1,2,3) [sum all data points for each species for each round]  /  # of rounds [usually 3]
> ·         Here are the values I did hard checks on:
> -   Table 1
>     -  All1 red clover: 1.5 in current table, 4 is true answer
>     -  All1 white clover: 106 in current table, 375.3 is true answer
>     -  Pio1 black eyed susan: 52.6 in current table, 210.3 is true answer
> -   Table 2
>     -  Nkn1 birdsfoot trefoil: 57.4 in current table, 574.3 is true answer
>     -  Nor1 blue vervain: 150.3 in current table, 501 is true answer

**Comment by jarad** [comment]
The code wasn't summing across the rounds first. Some of the answers now match your "true answers" but some don't. For example, there is only 2 rounds (round 1 and 3) for all1 and thus I believe the true answer should be 6.

**Comment by sethapp** [comment]
I think the true answer still is 4 and here's my explanation for what I think is going on.

For 'all1 red clover' the values are R1: 2, R2: 0, R3: 10. So a total of 12 red clover/3 rounds=4. Based on what you said, the formula is counting all rounds which don't have 'red clover' as an entry as NA instead of 0. All rounds where data is collected but a species is not recorded means the species was a zero and contributes to the overall average.

**Comment by jarad** [comment]
I agree. So what we need is to extract from the files every survey that occurred whether or not any species was recorded.

**Comment by nulloa** [comment]
Moved to jarad/ISUmonarch_figuresAndTables#3
