### ISSUE TITLE
NCIG Report: Table 5 nectar density calculated incorrectly

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#23]
From Seth:

> Sum(round 1,2,3) [sum all data points for each species for each round] /  transect length /  # of rounds [3]  * 100
> Here are the values I did hard checks on:
> -  Nkn1 birdsfoot trefoil: 862 in current table, 574.3 is true answer
> -  Nor1 blue vervain: 3006 in current table, 1002 is true answer

**Comment by jarad** [comment]
This is related to the calculation of length which is currently incorrect. It appears the data as read in from Site [Metadata Git 4-7-17.xlsx](https://github.com/jarad/ISUmonarch/blob/master/data-raw/Site%20Metadata%20Git%204-7-17.xlsx) is incorrect. For example,
```
> ISUmonarch::length %>% filter(site %in% c("nkn1","nor1"))
# A tibble: 2 x 2
  site  length
  <chr>  <dbl>
1 nkn1   200  
2 nor1    50.0
```

Running the current length.R script and looking at the created `length` object, we have 

```
> length %>% filter(site %in% c("nkn1","nor1"))
# A tibble: 6 x 3
  site   round  length
  <fctr> <chr>   <dbl>
1 nkn1   round1   50.0
2 nkn1   round2   50.0
3 nkn1   round3  100  
4 nor1   round1   NA  
5 nor1   round2   NA  
6 nor1   round3   50.0
```
We need to fix up this underlying data to get the correct densities.

**Comment by sethapp** [comment]
I actually don't think the underlying data is wrong but I think I have an idea of what is wrong. 

For 2016 the length changed for some transects. These are now highlighted in yellow in the metadata doc. For these sites we have to use the values in the three columns '2016_r1_transect_length' '2016_r2_transect_length' and '2016_r3_transect_length', which I think you're doing. 2016 data is tough as there aren't always 3 rounds of data.

For 2017 (and all other sites not yellow, those whose transect length didn't change). The column 'final_transect_length' should be used for all rounds. For 2017 this 'final_transect_length' would have to be multiplied by 3 to get total length for all three rounds. I am quite sure this is why 
"Nor1 blue vervain: 3006 in current table, 1002 is true answer" is three times greater than it should be. The calculation probably uses 50m (that was the total transect length for nor1 from 2016. nor1 only had data taken once for a total of 50m in 2016 while nor1 had data taken three times for a total of 150m in 2017. 

Both of the excerpts above are correct for the total and individual transect lengths in 2016. 2017 data has to based on 3x length (due to 3 rounds) of 'final_transect_length'.

**Comment by sethapp** [comment]
So the correct formula for this data for both 2016 and 2017 data would be:

Sum of species: round1+round2+round3  /  sum of transect lengths: round1+round2+ round3

The formula that only applies to 2017 would be:

Sum of species: round1+round2+round3  /  ('final_transect_length' * 3)

**Comment by jarad** [comment]
I think what we want to do is to create a length data.frame that would include each year and round and the length it that round. That way we can make the code consistent.

**Comment by sethapp** [comment]
should I just add that to the site metadata? It would require two more columns for 2017 at this point which is very easy

**Comment by jarad** [comment]
It is is going to be consistent from here on out, I think we just create it ourselves with a script based on "final_transect_length".

**Comment by sethapp** [comment]
I think you're asking if it will be consistent from here on out. The answer is yes, barring a farmer or field manager accidentally destroying part of it. "final_transect_length" is the length for all 2017 data and should never change for all data going forward
