### ISSUE TITLE
Which variables to itemize for .R help files

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#37]
In creating the help files it is clear to me (from the original nectar help file you made) that I should itemize the variables which are in "" from the R script files. I don't understand what other variables I should itemize. For the nectar help file (https://github.com/jarad/ISUmonarch/blob/master/R/nectar.R) how do I know to itemize 'distance' and 'count' since they aren't listed in the variables in the R script file (https://github.com/jarad/ISUmonarch/blob/master/data-raw/nectar.R). 

I'm attempting to figure this out as I look at the R scripts for other data types (https://github.com/jarad/ISUmonarch/blob/master/data-raw/bee.R) and create new helpfiles (https://github.com/jarad/ISUmonarch/blob/master/R/bee.R). On bee I put in 'nectar' on the helpfile but maybe it should say 'Nectar Plant Species'. I'm assuming I don't list 'Bee Species' or 'Pollinator Species' because that is contained under 'bee'

**Comment by jarad** [comment]
Related to #4

**Comment by jarad** [comment]
Nice work on getting the template for each of these data types up and running. We want to itemize all the variables that are actually in the associated data.frame. The best way to do this is to install the package, e.g. RStudio > Build > Install and Restart, and then look at the names in the data.frame, e.g. `names(bee)`. That will print out a list of the names. 

We should probably decide what we want the names to actually be. From issue #36, I see that you want to use observer rather than recorder and I will be able to make that change. For choosing other names, the trade-off is what is easy to use when working in R versus what looks good when you use the variable in a table, figure etc. For example, "Nectar Plant Species" is hard to work with in R because you always need to escape it with a backtick, but it looks nice in a table. The converse is that "nectar_plant_species" is easy to work with in R, but looks bad in a table. Right now, I am taking the names directly from the data files and thus we currently have "Nectar Plant Species" because that is what the data files use.

**Comment by sethapp** [comment]
Done
