### ISSUE TITLE
Misspellings in datasets

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch#49]
I'm working on the NCIG rmd script and specifically working on the nectar part of it. I'm looking at the nectar dataset and notice some typos in the data e.g. `sweet yellow clover` instead of `yellow sweet clover` or `yelllow sweet clover` instead of `yellow sweet clover`

For this case and in general, where should this be fixed? In the `nectar.R` script or back in the csv entry? 

@jarad @sethapp

**Comment by sethapp** [comment]
My first reaction is to fix it in the csv. Jarad, do you agree? Can a script be written to test every nectar line item against 
https://github.com/jarad/ISUmonarch/blob/master/data-raw/nectar/nectar_species_scientific_name_counting_unit.txt 
to find all typos? Then can some kind of output be made so that myself (or an undergrad) can go in and fix each typo? Or maybe we can fix typos with scripts?

**Comment by jarad** [comment]
I agree. Fix in the csv.

We could write a script, but I think it would be better to create a test. To create a test, we first need to create an R data.frame that has the information contained in that txt.

**Comment by nulloa** [comment]
So I have created a `species.R` script which creates a `species` data.frame containing the above csv.

**Comment by nulloa** [comment]
The test in 791b997b6d3f59bb7e4632e9bacf61b655e4e0bd prints out the wrong names in nectar dataset. Still need to go in an fix them.

**Comment by sethapp** [comment]
Great @nulloa . Can you help me figure out what I'm doing wrong because I can't seem to run it correctly. I downloaded the testthat package first. I tried to run it two ways; with working directory set to 'data-raw' and also with working directory as 'nectar'. Got the same result.

![image](https://user-images.githubusercontent.com/22353630/52420928-a5788980-2ab8-11e9-9fc5-d00a3ba3974c.png)

**Comment by nulloa** [comment]
@sethapp hmmm....I just run it like this in Rstudio:

![image](https://user-images.githubusercontent.com/5848093/52450145-70dbf080-2aff-11e9-8a41-3774001e2582.png)

It won't matter the working directory. Just click on 'test package' from that menu.

**Comment by sethapp** [comment]
@nulloa since I don't know much about R/Rstudio it's difficult for me to troubleshoot things. The best approach to communicating steps to me is to either screenshot or PDF the end result or to give me a step by step of what to do to reproduce what you're telling me to do.
 
Yesterday I wasn't doing 'build' > 'test package' because I didn't know to do that. I guessed that I needed to run the actual code in the 'test-names.R' file. The result I sent yesterday is what appeared in the console when I ran that code.

I did what your picture showed and this is what I got. 
![image](https://user-images.githubusercontent.com/22353630/52489122-0bcbdd80-2b87-11e9-82dd-d50637811613.png)
I don't know how to tell it I want it to work in the 'testthat' folder not the 'tests' directory.

@jarad Also, is the 'testthat.R' file being used for anything? It looks like it's old or not doing anything. Should we delete it?

**Comment by nulloa** [comment]
I've never gotten that error but on Tuesday, I can try troubleshooting your setup. I'll fix the misspellings for now.

**Comment by nulloa** [comment]
`butterfly milkweed ramet`, `common milkweed ramet`, `swamp milkweed ramet` aren't in the common names listed in [species dataset](https://github.com/jarad/ISUmonarch/blob/master/data-raw/nectar/nectar_species_scientific_name_counting_unit.txt) but it used 1939, 1938, 1939 times respectively in the nectar dataset. Are these really not the proper name?

Also `field bindweed`, `ox eye susan`, `self heals`, `smartweed`(which I'm assuming is pennsylvania smartweed), `sweet clover`, `tall goldenrod` exist in nectar but not at all in the species names.

I don't know what to do with `milkweed strip: common milkweed ramet`, `milkweed strip: common milkweed strip`

Also there's an inconsistencies in the species names like `ox eye sunflower` and `ox-eye daisy`. Is this how it is supposed to be?

**Comment by sethapp** [comment]
`butterfly milkweed ramet`, `common milkweed ramet`, `swamp milkweed ramet` are counting ramets of each of these species, not floral counting units. They are basically a separate data set that was collected at the same time and over the same area as the nectar survey. They should be summarized in a separate table like Jarad did in the NCIG report, table 3 and 6. So it is correct that they are not included in the species name list. 

For all names changes I'm assuming I will need to go in and change the actual csv's
'field bindweed' = 'morning glory'
'ox eye susan'...if you can tell me which data entry this comes from I'll try to figure out what this should actually be
'self heals' = 'common selfheal'
'smartweed' = @jarad  I learned that our team was not able to differentiate pennsylvania smartweed vs swamp smartweed. I think I should just combine the two into 'smartweed'. The question then is do I change this in the csv's or can we do something with the script to change it? Also, I probably need to change the nectar species common names list if I do this. 
'sweet clover'......if you can tell me which data entry this comes from I'll try to figure out what this should actually be
'tall goldenrod' = 'canada goldenrod'

'milkweed strip: common milkweed ramet' is the wording that should be used; not 'milkweed strip: common milkweed strip'. This data will only exist for nkn1, arm1, ber3, and all2 in 2017,2018. For some rounds it will be missing because the team forgot to collect the data. This data should go in a separate table on its own (in the same manner as the milkweed ramets data) as it is not part of the 'nectar survey'.

'ox eye sunflower' should always be 'ox eye sunflower'
'ox eye daisy' should always be 'ox eye daisy'
These are different species
No names should have any dashes in them

**Comment by nulloa** [comment]
For the `ramet` names, create a separate `ramet` data.frame in the `nectar.R` file pulling from `nectar` the plants with these three names. 


See #56

**Comment by nulloa** [comment]
#56

**Comment by jarad** [comment]
Also a line in [nectar species file](https://github.com/jarad/ISUmonarch/blob/master/data-raw/nectar/nectar_species_scientific_name_counting_unit.txt) with common name smartweed needs to be added.

**Comment by sethapp** [comment]
nectar species file had been updated. All misspellings have been fixed except for the ones which are not actually part of the dataset and 'smartweed' since it is new. 'Smartweed' line was added and swamp/pennsylvania smartweed was removed.

![image](https://user-images.githubusercontent.com/22353630/52813966-9a959a00-3060-11e9-8f1a-c12d0ceb6da6.png)

Once the 'smartweed' changes are incorporated we can close this issue I believe.

**Comment by nulloa** [comment]
Fixed with 55a1e9398651aae003471d2f738d445e9084b146
