### ISSUE TITLE
Smartweed Issue

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#57]
@jarad see this csv https://github.com/jarad/ISUmonarch/blob/master/data-raw/nectar/2017/07/14/RoyceB/fis1_tfis1a_2.csv

Will this be an issue or will they all be collapsed into one line in the analysis? This site had pennsylvania, swamp, and 'they were not sure which one' smartweed; hence the three lines.

**Comment by jarad** [comment]
It won't be collapsed automatically, but any analysis in the future that summarizes by smartweed will be collapsed. 

Nonetheless, I suggest we modify the csv file to only have a single line that is the sum of the other lines since future data will be collected in this manner. In addition, we could add a README to this directory to explain why this was done. 

But if this problem exists in a large number of files then we should just adjust the script to collapse/aggregate appropriately.

**Comment by sethapp** [comment]
Fixed the csv. Wrote a new readme for this specific file and updated 'nectar' readme to explain smartweed decisions
