### ISSUE TITLE
Create new data.frame with grant

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch#65]
We need to create a new data.frame containing the grant associated with each site. Should this be combined with the `transect` data.frame? @sethapp @jarad

**Comment by sethapp** [comment]
that makes sense to me

**Comment by sethapp** [comment]
I added a csv on which the data frame can be based. It contains the 'grant' and the new siteID and transectID for the locations we changed in order to follow a standard set of rules.
https://github.com/jarad/ISUmonarch/blob/master/data-raw/transect/transect.csv

As noted here and in #66 the data frame needs to include the new siteID and transectID changes
